default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") {'postgres'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {'Martial@5009'} %>


development:
  <<: *default
  database: leDjen_development
  username: <%= ENV.fetch("DATABASE_USERNAME") {'postgres'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {'Martial@5009'} %>

test:
  <<: *default
  database: LeDjen_test
  username: <%= ENV.fetch("DATABASE_USERNAME") {'postgres'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {'Martial@5009'} %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: LeDjen_production
  username: LeDjen
  password: <%= ENV["LEDJEN_DATABASE_PASSWORD"] %>
